version: '3.8'

services:
  app:
    build: .
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - NODE_ENV=development

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: ms-products-rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: ms-products-mongodb
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5