version: '3.8'

services:
  app:
    build: .
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env
    networks:
      - ms-product-network

  rabbitmq:
    image: rabbitmq:3.6-management
    container_name: ms-products-rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      retries: 5
    networks:
      - ms-product-network

  mongodb:
    image: mongo:latest
    container_name: ms-products-mongodb
    restart: always
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - ms-product-network

networks:
  ms-product-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

volumes:
  mongo_data:
